#!/usr/bin/env python3
"""Standalone recompute check for the published calibration tables.

Reads calibration_observations.jsonl and re-derives threshold_table.json
and sensitivity.json with no dependency on the generating codebase; a
mismatch prints the file name and exits 1. malformation_eval.json is
generated by the corpus module at the recorded seed and is out of scope
here (it needs the DAG code); its inputs are stated in the file itself.
"""
import json
import sys

GATE = {"real": {"min_closeness": 0.80, "entropy_cap": 3.2},
        "sim": {"min_closeness": 0.80, "entropy_cap": 1.5}}


def pct(sv, q):
    if not sv:
        return None
    return sv[min(int(round(q * (len(sv) - 1))), len(sv) - 1)]


def tables(rows):
    tt, sens = {}, {}
    for key, src in (("real", "proof_term"), ("sim", "simulator_shaped")):
        sub = [r for r in rows if r["dag_source"] == src]
        ent = sorted(r["step_label_entropy"] for r in sub
                     if r["step_label_entropy"] is not None)
        lc = sorted(r["logical_closeness"] for r in sub
                    if r["logical_closeness"] is not None)
        tt[key] = {"n_accepts": len(sub),
                   "step_label_entropy": {"median": pct(ent, .5), "p75": pct(ent, .75),
                                          "p95": pct(ent, .95), "p99": pct(ent, .99),
                                          "max": ent[-1] if ent else None},
                   "logical_closeness": {"min": lc[0] if lc else None,
                                         "p05": pct(lc, .05), "median": pct(lc, .5)},
                   "active_thresholds": GATE[key]}
        if not ent:
            sens[key] = None
            continue
        cuts = {"p95": pct(ent, .95), "p99": pct(ent, .99), "max": ent[-1],
                "active": GATE[key]["entropy_cap"]}
        sens[key] = {n: {"cap": c,
                         "false_quarantines": sum(1 for e in ent if e > c),
                         "rate": round(sum(1 for e in ent if e > c) / len(ent), 4)}
                     for n, c in cuts.items()}
    return tt, sens


def main():
    rows = [json.loads(l) for l in open("calibration_observations.jsonl",
                                        encoding="utf-8") if l.strip()]
    tt, sens = tables(rows)
    for name, fresh in (("threshold_table.json", tt), ("sensitivity.json", sens)):
        published = json.load(open(name, encoding="utf-8"))
        if published != json.loads(json.dumps(fresh)):
            print(f"MISMATCH: {name}")
            return 1
    print(f"OK: {len(rows)} observations; threshold_table and sensitivity re-derive.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
